# Variables:
#   enroll_name       : ${ENROLL_NAME}
#                     : enroll
#   rap_domain        : ${DOMAIN_NAME} 
#                     : rap.tarski.nl

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enroll-ingress
  namespace: ${ENROLL_NAME}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ${ENROLL_NAME}.${rap_domain}
      secretName: ${ENROLL_NAME}-tls
  rules:
    - host: ${ENROLL_NAME}.${DOMAIN_NAME}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: ${ENROLL_NAME}
                port:
                  number: 80

