name: Azure Connect

on:
  push:
  workflow_dispatch:


jobs:
  azure-connect:
    environment: Local${{github.actor}}
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az group list --query [].name
      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
          inlineScript: Get-AzResourceGroup -Name "VisualStudioOnline-9E00E7D74D544D068151FEA4A5C21C76"
          azPSVersion: "latest"      
      
