# This is a basic workflow to help you get started with Actions

name: CICD Pipeline

# Controls when the workflow will run
on:
  push:
    branches: 
      - development
      - a_feature
  pull_request:
    branches: 
      - development
      - a_feature

env:
  workflow_variable: "workflow value"  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "build"
  Development:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Development

    env:
      job_variable: "job value"  

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v3

      - name: Echoing variables
        env:
          step_variable: "step value"  
        run: |
          echo Echoing workflow_variable * $workflow_variable *
          echo Echoing job_variable * $job_variable * 
          echo Echoing step_variable * $step_variable * 

      - name: Echoing github context variables
        run: |
          echo Echoing github.actor * ${{ github.actor }} *
          echo Echoing github.base_ref * ${{ github.base_ref }} *
          echo Echoing github.ref_name * ${{ github.ref_name }} *
          echo Echoing github.repository * ${{ github.repository }} *
          echo Echoing github.run_id * ${{ github.run_id }} *
          echo Echoing github.workflow * ${{ github.workflow }} *

      - name: Echoing vars context variables
        run: |
          echo Echoing vars.AVARIABLE * ${{ vars.AVARIABLE }} *

      - name: Echoing secrets context variables
        run: |
          echo Echoing secrets.ASECRET * ${{ secrets.ASECRET }} *
      
      - uses: log_vars_action


  Staging:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Staging
    needs: Development

    env:
      job_variable: "job value"  

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v3

      - name: Echoing variables
        env:
          step_variable: "step value"  
        run: |
          echo Echoing workflow_variable * $workflow_variable *
          echo Echoing job_variable * $job_variable * 
          echo Echoing step_variable * $step_variable * 

      - name: Echoing github context variables
        run: |
          echo Echoing github.actor * ${{ github.actor }} *
          echo Echoing github.base_ref * ${{ github.base_ref }} *
          echo Echoing github.ref_name * ${{ github.ref_name }} *
          echo Echoing github.repository * ${{ github.repository }} *
          echo Echoing github.run_id * ${{ github.run_id }} *
          echo Echoing github.workflow * ${{ github.workflow }} *

      - name: Echoing vars context variables
        run: |
          echo Echoing vars.AVARIABLE * ${{ vars.AVARIABLE }} *

      - name: Echoing secrets context variables
        run: |
          echo Echoing secrets.ASECRET * ${{ secrets.ASECRET }} *

