# This is a basic workflow to help you get started with Actions

name: CICD Pipeline

# Controls when the workflow will run
on:
  push:
    branches: 
      - development
      - a_feature
  pull_request:
    branches: 
      - development
      - a_feature

env:
  workflow_variable: "workflow value"  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      job_variable: "job value"  

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v3

      - name: Echoing variables
        env:
          step_variable: "step value"  
        run: |
          echo Echoing workflow_variable * $workflow_variable *
          echo Echoing job_variable * $job_variable * 
          echo Echoing step_variable * $step_variable * 

      - name: Echoing github context variables
        run: |
          echo Echoing github.action * ${{ github.action }} *
          echo Echoing github.action_path * ${{ github.action_path }} *
          echo Echoing github.actor * ${{ github.actor }} *
          echo Echoing github.base_ref * ${{ github.base_ref }} *
          echo Echoing github.ref * ${{ github.ref }} *

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
