# This is a basic workflow to help you get started with Actions

name: CICD Pipeline

# Controls when the workflow will run
on:
  push:
    branches: 
      - development
      - a_feature
  pull_request:
    branches: 
      - development
      - a_feature

env:
  env_name: "*${{ vars.ENVIRONMENTNAME }}*"  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Echoing variables
        run: |
          echo Echoing GITHUB_REPOSITORY * ${{ vars.GITHUB_REPOSITORY }} * 
          echo Echoing env_name * ${{ vars.env_name }} * 
          echo "Echoing ENVIRONMENTNAME * ${{ vars.ENVIRONMENTNAME }} *" 
          echo "Echoing VNAME * ${{ vars.VNAME }} *" 
          echo "Echoing ASECRET * ${{ secrets.ASECRET }} *" 

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
