# This is a basic workflow to help you get started with Actions

name: Test Workflow

# Controls when the workflow will run
on:
  push:
    branches: 
      - development
      - a_feature
  pull_request:
    branches: 
      - development
      - a_feature

env:
  workflow_variable: "workflow value"  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  PreEchoVariables:
    environment: Local${{ github.actor }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Pre Echoing variables
        run: |
          echo Echoing github.actor * ${{ github.actor }} *
          echo Echoing vars.is_local_env * ${{ vars.is_local_env }} *

  Local:
    uses: ./.github/workflows/Deploy_workflow.yml
    with:
      env_name: Local${{ github.actor }}

  Development:
    needs: Local
    uses: ./.github/workflows/Deploy_workflow.yml
    with:
      env_name: Development

  Staging:
    needs: Development
    if: github.ref_name == 'development'
    uses: ./.github/workflows/Deploy_workflow.yml
    with:
      env_name: Staging
