# This is a basic workflow to help you get started with Actions

name: Test Workflow

# Controls when the workflow will run
on:
  push:
    branches: 
      - development
      - a_feature
  pull_request:
    branches: 
      - development
      - a_feature

env:
  workflow_variable: "workflow value"  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  Local:
    environment: 'Local${{ github.actor }}' 
    uses: ./.github/workflows/Deploy_workflow.yml
    with:
      env_name: 'Local${{ github.actor }}'

  Development:
    needs: Local
    uses: ./.github/workflows/Deploy_workflow.yml
    with:
      env_name: Development

  Staging:
    needs: Development
    if: github.ref_name == 'development'
    uses: ./.github/workflows/Deploy_workflow.yml
    with:
      env_name: Staging
