name: CICD Pipeline

on:
  push:
    branches: 
      - development
      - 'feature/**'
  pull_request:
    branches: 
      - development
      - 'feature/**'
  workflow_dispatch:

jobs:
  PreCheck:
    environment: LocalFrankTeusink
    runs-on: ubuntu-latest
    env:
      XXX: ${{ secrets.FRANKIES_SECRET}}
    steps:
      - name: Echoing variables
        run: |
          echo Echoing vars.enroll_name: ${{ vars.enroll_name }}
          echo Echoing vars.domain_name: ${{ vars.domain_name }}
          echo Echoing XXX: ${{ env.xxx }}

  Local:
    if: startsWith(github.ref_name, 'feature/')
    uses: ./.github/workflows/Deploy_workflow.yml
    with:
      environment_name: 'Local${{ github.actor }}'

  Development:
    if: github.ref_name == 'development'
    uses: ./.github/workflows/Deploy_workflow.yml
    with:
      environment_name: Development

  Staging:
    needs: Development
    if: github.ref_name == 'development'
    uses: ./.github/workflows/Deploy_workflow.yml
    with:
      environment_name: Staging
