name: Deploy workflow

on:
  workflow_call:
    inputs:
      environment_name:
        description: Name of the environment to which is deployed
        required: true
        type: string

jobs:
  
  EchoVariables:
    environment: '${{ inputs.environment_name }}'
    runs-on: ubuntu-latest
    steps:
      - name: Echoing variables
        run: |
          echo Echoing github.actor * ${{ github.actor }} *
          echo Echoing inputs.environment_name * ${{ inputs.environment_name }} *
          echo Echoing vars.ENVIRONMENT_NAME * ${{ vars.ENVIRONMENT_NAME }} *
      
  Deploy:
    environment: '${{ inputs.environment_name }}'
    if: ${{ vars.ENVIRONMENT_NAME == inputs.environment_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo Deploying....


