# This is a basic workflow to help you get started with Actions

name: CICD Pipeline

# Controls when the workflow will run
on:
  push:
    branches: 
      - development
      - a_feature
  pull_request:
    branches: 
      - development
      - a_feature

env:
  workflow_variable: "workflow value"  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "build"
  Development:
    uses: ./.github/workflows/Deploy_workflow.yml
    with:
      env_name: Development
      run_if: true

#  Staging:
#    if: github.ref_name == 'development'
#    uses: ./.github/workflows/Deploy_workflow.yml
#    with:
#      environment: Staging
#      runif: true
