name: Play With Secrets Subcall

on:  
  workflow_call:
    inputs:
      enroll_name:
        description: Name of the environment to which is deployed
        required: false
        type: string
      frankies_secret:
        description: frankies secret
        required: false
        type: string

jobs:
  ProcessCall:
    environment: LocalFrankTeusink
    env:
      enroll_name: ${{ inputs.enroll_name }}
      env_frankies_secret: ${{ inputs.FRANKIES_SECRET }}
    runs-on: ubuntu-latest
    steps:
      - name: Echoing variables
        run: |
          echo Echoing vars.enroll_name: ${{ vars.enroll_name }}
          echo Echoing inputs.enroll_name: ${{ inputs.enroll_name }}
          echo Echoing inputs.enroll_name: ${{ inputs.enroll_name }}
